### ISSUE TITLE
Take associatedStreet into account to connect streets with houses

### ISSUE THREAD

**Issue by sfkeller** [OSMNames/OSMNames#103]
Relation type 'type=associatedStreet' (and 'type=street') is used to connect streets to houses for addressing purposes.
Taginfo reports currently >5 mio. worldwide: https://taginfo.openstreetmap.org/relations/associatedStreet . Pls. read https://wiki.openstreetmap.org/wiki/Relation%3AassociatedStreet to understand this tag and the differences to the preferred "addr:*" tagging.

**Comment by philippks** [comment]
:+1: already done if `associatedStreet` or `street` relation with an `name` or `addr:street` attribute exists.

As part of this issue I'll search for other relation members with the role `street` and use the name to complete the housenumbers. This is necessary since sometimes the relation itself does not have a `name` or `addr:street` attribute.

**Comment by sfkeller** [comment]
Nice! So just close this issue and move it to Done!
