### ISSUE TITLE
Slow Export

### ISSUE THREAD

**Issue by alexsteinerde** [OSMNames/OSMNames#165]
Hey,

I'm trying to run the project with the provided docker command. I had to move the code to an external hard drive due to less space. The import of all the data works fine everytime. But now the exporting is already running for over 24h and has not yet passed 10%.
What am I doing wrong?
Can I reduce any steps because I only want to use this data for reverse geocoding with the provided api in the other repo?

Thanks for your help,
Alex

**Comment by philippks** [comment]
hey @alexsteinerde 

I assume you're processing the osm data for the whole planet? It is true, this takes very long. When I'm processing the data for a new release, it takes up to 40 hours... and this on a very strong machine.

But since you only need the output, you can simply download it here:
https://github.com/OSMNames/OSMNames/releases

The file planet-latest_geonames.tsv.gz contains the output for the whole planet.

Does this solve your problem?

**Comment by alexsteinerde** [comment]
Hey @philippks 

Thank you for your fast answer. Yes I use the osm data for the whole planet. Ok, so I'm it's not a problem, it happens all the time.
Ok, thanks for the tip with the prepared data.
Thanks.
