### ISSUE TITLE
Invalid lines in data version 1.1 (World/Planet)

### ISSUE THREAD

**Issue by MartinMikita** [OSMNames/OSMNames#44]
Total lines in input file: 21 055 840
Processed lines: 21 055 701

Invalid lines: 139

See attached tsv, ods and xls files packed in ZIP
[planet-1.1-invalid-lines.zip](https://github.com/geometalab/OSMNames/files/459484/planet-1.1-invalid-lines.zip)

BTW command for checking:
`cat data.tsv | sed -e 's/\r/ /g' | awk -F"\t" 'NR > 1 && NF != 23 {print NR"\t"$0}' > data-invalid-lines.tsv`

**Comment by and01** [comment]
Analyzing the data, it seems that there are still a few problem records:

- Some records miss a rank (`place_rank=0`). This value however is crucial to the whole hierarchy process and therefore lead to other missing values. It seems that these entries are all of type `administrative`. In this case it should then calculate a rank based on the `admin_level` and otherwise have a default rank of 30. It looks like this `2*(SELECT COALESCE(admin_level,15)`. The culprit lies there somewhere.
- Other records seem to be on a mystery island: https://www.openstreetmap.org/way/404422270#map=15/-11.4282/86.4264
With this false data OSMNames cannot put a country code to it and consequently fails to calculate dependent fields. I suggest to drop such values in the importing process.

**Comment by mtmail** [comment]
I left a changeset comment on the mystery island https://www.openstreetmap.org/changeset/37924244, it's tagged as place but doesn't render on the map. Also I can't find a secondary source that such an island exists.

**Comment by sfkeller** [comment]
I've fixed the mystery island data https://www.openstreetmap.org/changeset/37924244 by deleting it in OSM :-) .

**Comment by simran001** [comment]
May be related to fields with null values (missing parents).

**Comment by sfkeller** [comment]
Maybe related to pgclimb which does not export null values as an empty field value?

**Comment by philippks** [comment]
pgclimb did not export NULL values as empty strings why some rows had an invalid amount of columns. Since pgclimb has been replaced with the COPY command of Postgres, the problem is solved.

The newest output of the planet does not contain any invalid lines.
