### ISSUE TITLE
Importance for streets

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#46]
OSMNames seems to have the same importance value for a street in a capital town to an equally named street in a village.

For fulltext search results (without viewbox provided) the streets in big cities should be shown first. That's what Google does too.

**Comment by sfkeller** [comment]
Good point! Would'nt call it a bug though. Should we introduce a new label "enhancement" for such issues?

**Comment by klokan** [comment]
I think it is bug - as Nominatim has importance of streets calculated already:
http://nominatim.openstreetmap.org/?q=namesti+svobody&polygon=1

@and01 - is this something extremely easy to fix. Could you give us a tip where in the code is this?

**Comment by klokan** [comment]
In fact on a test query: "namesti svobody" (the "freedom square" - the main square in Brno - my home town) in many villages the records with the same name has standard constant importance 0.1. For "Brno" town with a higher importance thanks to wikipedia - it has LOWER then default `"importance": 0.075,`! Looks really like a bug in calculation of the importance.

**Comment by and01** [comment]
This must be a bug in the wikipedia matching code in the getImportance function. Nominatim matches the wikipedia entry to cs:Náměstí_Svobody_(Brno) whereas OSMNames doesn't have one hence calculating an importance based solely on the rank itself.

**Comment by simran001** [comment]
Hi everyone,

Just found out that this was not a bug in the wikipedia matching code. The [Náměstí Svobody (osm_id = 4934858)](http://www.openstreetmap.org/way/4934858#map=18/49.19474/16.60809) that we were searching for wasn't being imported in OSMNames, since the tag `highway:pedestrian` was not included in the mapping file. Instead, OSMNames was returning the results for another highway [Náměstí Svobody (osm_id = 50285100)](http://www.openstreetmap.org/way/50285100#map=18/49.19503/16.60795), of the type `highway:service`. This element does not have any wikipedia importance attached to it.

Moreover, the Náměstí Svobody (Freedom Square), is also a special case because it is a highway of polygon type. Solved this issue with PR #93 by including `highway:pedestrian` in the osm_linestring and osm_polygon tables in the [mapping file](https://github.com/simran001/OSMNames/blob/master/data/import/mapping.yml#L28). Now it has an importance of 0.282240924205224, as fetched from wikipedia, the same as Nominatim.
