### ISSUE TITLE
Complete alternative_names

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#56]
This is improvement of #37 

> "alternative_names" should contain every unique alternative name of a place, but the one already visible in the "name" column - all separted by comma. 

Right now only 7 languages are exported. It would be practicaly to make a complete export, when possible (of all unique alternative names).

**Comment by sfkeller** [comment]
Don't know yet what's the best solution. 
Do you mean to put more/all - available and distinct - names into "alternative_names"?
Or should we put the names as key-value-pairs in "alternative_names"? (there are 184 attributes for all currently registered two-letter codes of ISO 639-1 :-) 
What about Wikidata which has even more names?
And what about OSM attributes "int_name, loc_name, nat_name, official_name, old_name, reg_name, short_name, alt_name, name_1" (as indicated here https://wiki.openstreetmap.org/wiki/Key:name )?

**Comment by klokan** [comment]
For the fulltext applications we need only list of all distinct alternative names - hardly ever place have 184 different names - usually many languages call the place the same...

Concatenation of everything distinct in one string is fine.
We create a derivative and "fulltext optimised" export here...

The use case I am trying to solve is that users of our products in Netherlands search for place names in dutch, but they don't get any results now.
They would be fine to choose from suggested place name (with English `name_en` or original `name` title), but now nothing comes up - because dutch is not one of the languages we export and index in OSMNames...

**Comment by simran001** [comment]
Resolved with Pull Request #71

**Comment by simran001** [comment]
Hi @sfkeller and @klokan, just an update about this issue. 

A pattern matching like the following is done in [set_names.sql](https://github.com/OSMNames/OSMNames/blob/master/osmnames/import_osm/set_names.sql#L10) to extract all the `name` tags:
```WHERE key LIKE 'name:%' OR key LIKE '%[_]name'```

Hence the values for all of the following keys will be included in alternative names:

- name
- name:&lt;lg&gt; (for example name:de, name:en)
- name:left
- name:right
- int_name
- loc_name
- nat_name
- official_name
- old_name
- reg_name
- short_name
- sorting_name
- alt_name
- nat_name:<lg>

I referred to the [Openstreetmap wiki](http://wiki.openstreetmap.org/wiki/Key:name) to ensure that all the name keys defined there are considered.

**Comment by sfkeller** [comment]
That look OK to me - except for the sorting_name which probably does not belong here (but I can live with it).

**Comment by klokan** [comment]
It would be very VERY good to synchronise this effort with https://github.com/openmaptiles/openmaptiles/issues/211
and
https://github.com/klokantech/openmaptiles/blob/multilinguality/openmaptiles.yaml#L27

**Comment by sfkeller** [comment]
This issue is about the field alternative_names which serves the search process. These 30 languages are already covered and a subset of what's going into this field.
@klokan: You may look at #55 (and comment on it) which is more similar to the "multilinguality" requirement of OMT.

**Comment by simran001** [comment]
Just documenting a change I made in the code related to this issue. I realized that the pattern-matching `WHERE key LIKE 'name:%' OR key LIKE '%[_]name'` would also select some name tags that we do not want to include, for example `name:prefix` (please see issue #84 and search results for `name` on [taginfo](https://taginfo.openstreetmap.org/search?q=name)). With PR #82 I have implemented a stricter check in [get_alternative_names()](https://github.com/OSMNames/OSMNames/blob/master/osmnames/import_osm/set_names.sql#L12) to include only the following tags as defined in the [Openstreetmap wiki](http://wiki.openstreetmap.org/wiki/Key:name).

- name:&lt;lg&gt; (names in all available languages, for example, name:de, name:en)
- name:left
- name:right
- int_name
- loc_name
- nat_name
- official_name
- old_name
- reg_name
- short_name
- alt_name

Hence, we exclude the `sorting_name` tag too, since Prof Stefan (@sfkeller) mentioned that it does not belong here. :)
