### ISSUE TITLE
Duplicate row for places in dataset

### ISSUE THREAD

**Issue by sanketkumarsingh** [OSMNames/OSMNames#61]
Hi,

I dowloaded the full Planet dataset from http://osmnames.org/download/ 
and try to use the display name column to create hierarchy using OSMID's so that I can use the dataset for my research.

I saw several instances where data for same place is repeated . For example : "NU, Nunavut, Canada" display name,  occur in around 435 rows. Could you please let me know how to determine which one is the golden or best record for given place in this scenario. Is it based on last updated? I couldn't find any date columns at row level.

Sorry, I asked the question here as I am not aware if there is any forum for OSMNames.

Thank you so much for dataset.

Awaiting response!

**Comment by sfkeller** [comment]
I think there's nothing to do for you now but picking the first one.

You found an unwanted output of OSMNames which is based on an administrative boundary which consists of a multipolygon with many outer boundaries. The input is an OSM relation having that many ways (e.g. http://www.openstreetmap.org/relation/390840). 

I think OSMNames should be enhanced in order to cope better with multipolygons.

**Comment by klokan** [comment]
+1 on enhancements for multipolygons

It could be practical to make a fork with extra output: triples with osmId/osmType + relation + osmId/osmType

Contributions are very welcome... ;-)

**Comment by sanketkumarsingh** [comment]
Thank you all for response. I will pick the first one as of now. Also, I was wondering how the bounding box in search response was formed? Is it based on all the places which are part of parent location (taking minimum and maximum of latitude and longitude for south west and north east bounds) or it is separate information available.

Thanks

**Comment by philippks** [comment]
There're no duplicate entries for the example "Nunavut, Canada" anymore. I think the issue is solved then? If not, a new issue with a concrete example should be created.

@sanketkumarsingh better late than never: the bounding box is not build based on the places inside an element. It is determined with the geometry of the element (e.g. the relation), which is imported from the openstreetmap data.
