### ISSUE TITLE
New release + downloadable dump

### ISSUE THREAD

**Issue by klokan** [OSMNames/OSMNames#97]
When is planned the next new release (2.0?) with the downloadable generated data for the whole planet?

Similar to:
https://github.com/OSMNames/OSMNames/releases

It seems the new tickets did not have any assigned milestones...
https://github.com/OSMNames/OSMNames/milestones

Thank you a lot for all the effort @simran001 @philippks and @sfkeller!

Is there any announcement planned?
Have you managed to modify the osmnames-sphinxsearch in your branch - to use the export of house addresses as well?
Or what are the tools where you use it?
What are the next plans?

**Comment by sfkeller** [comment]
Thanks Petr @klokan. @philippks definitely has plans to release another version of the planet in same TSV format. 

He currently uses a different planning tool. It could be an instructive experience for him to assign Github milestones. I'll discuss that with him and we communicate back.

I fear @philippks won't have time to make a pull request to osmnames-sphinxsearch since he should focus on house number extraction. 

I'm aware you proposed another field "house_numbers" to the main TSV containing a list of house numbers for a street in #49. The house_numbers list would be not such a big deal, but the zip clodes which is unclear to me how add them to this list (see below).

Be aware that the geocoding (search) engine is quite a different beast and these TSVs are "only" the input. E.g. a geocoder (search) engine has to guess the user's search input, e.g. needs to distinguish what is the zip code and what is the house number. This is something even Nominatim has problems just because zip codes are mising. E.g. libpostal - being another potential consumer of this TSV - will do that probably better than Sphinx-Search.

As mentioned, unfortunately the "zip" codes will be missing mostly in the TSV since they're missing in OSM. And zip codes ultimately belong to the housenumber's TSV.
=> How would you integrate zip codes in a flattened house_numbers list in the main TSV? 

That's why we proposed that somebody from Klokan Tech could change osmnames-sphinxsearch to accept (or ignore) at least the street-id as an additional field in the TSV in a next step. 

Given my thoughts above, 
=> do you still think it's worth @philippks adds also a search field "house_numbers" (without zip)?
=> and do you have resources to make the respective changes in osmnames-sphinxsearch on your part?

**Comment by philippks** [comment]
@klokan sorry for the delay on my side. The next 4 weeks I'll be absorbed by the exams. I'll continue my work on OSMNames in the mid of July and contact you as soon I've news.

**Comment by klokan** [comment]
Hi! I am keen to synchronise on the release of the new OSMNames data dump.

I have created a new milestone v2.0:
https://github.com/OSMNames/OSMNames/milestone/11

Could you please @sfkeller and @philippks assign the issues which:
- you still want to finish in this milestone (on which you work on actively now)
- were already implemented on this sprint (since the release of v1.1)

The task which are not sure when (or if) happens - please leave without milestone for now.

Based on the tickets/issues we normally prepare the release notes / changelog.

The release, once done, should contain the sorted gzipped data of the whole planet - so we can update the download links on the public website too. Are you able to prepare the data and upload it to the release @philippks ?

We will definitely be upgrading our instance with SphinxSearch - to bring in the in the latest global data - including multilingual alternatives and fixes on hierarchy and ranking you have made. Thanks!

We are keen to integrate also the address / housenumber search functionality too - but I am not sure when we find free time to do the implementation.
The osmnames-sphinxsearch code should load the final address lat/lon from an external SQLite database (with structure equal to the house address TSV), after the fulltext search validates the correctness of the address and provides the osm-id for the street record. A regular expression should probably try to extract the relevant house number from the user's query and ask the SQLite.

Happy to guide anybody interested in making the implementation - if you are willing to work on this and make a pull request to sphinx-search.
BTW we have just got a first external contribution implementing reverse geocoding...

Let's finish this release and go out with the new data soon...

Thanks for working on this project! 

Ping to @MartinMikita

**Comment by philippks** [comment]
Hi @klokan 

Thank you for creating the milestone. I planned to create it this week too. I'll assign the issues until tomorrow and create some more. The due date for the release is end of July. And yes, I'll create a dump with the newest changes for you, when all the issues are solved.

Right now I'm doing good progress with the housenumbers. I can provide you an example output for Switzerland or another country if you're interested.

**Comment by klokan** [comment]
Perfect. Thanks a lot @philippks - amazing job!

**Comment by philippks** [comment]
Release 2.0 published

**Comment by MartinMikita** [comment]
Thanks a lot @philippks !

Just a few questions:
  - What is the difference between geonames and housenambers tsv.gz files in the [release](https://github.com/OSMNames/OSMNames/releases/tag/v2.0)?
 - Are these tsv.gz files sorted by the `importance` now? See #51 and [osmnames-sphinxsearch](https://github.com/klokantech/osmnames-sphinxsearch#input-datatsv-format)
 - Is there a reason, why you have take out the output TSV format from README? In my opinion, it is most important information and it should be visible right in this repository in README section (Same as it is in osmnames-sphinxsearch input format)

**Comment by philippks** [comment]
Hi @MartinMikita 

* The geonames TSV does contain all the street, countries, towns and so forth, as before. The housenumbers TSV does contain each house number, with a linked osm_id and the coordinates. Both formats are described in the new documentation, which is not yet built.

* No the file is not sorted. I didn't know that it should be. I can do the sorting right now.

* I removed the format from the README because of the redundancy with the documentation. Counting `http://osmnames.org/download/` too, the format is described at three different places. In my opinion, the format should be described at one place only.

**Comment by MartinMikita** [comment]
Yes, please, sort the geonames TSV file and replace (or probably just add another one) into release.

OK, in that case it could be as it is now, link to the working documentation, where output format is directly visible on the first page is enough.

**Comment by MartinMikita** [comment]
Please, close this issue, when sorted TSV is in the release.

**Comment by MartinMikita** [comment]
Btw, could you write here the final number of lines in the geonames TSV? Thanks.

**Comment by philippks** [comment]
@MartinMikita the TSV is now sorted.

The file has now 23 559 356 lines.
